# -*- coding: utf-8 -*-
"""pandas-0510

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D16xPn-xQ-jQGxCx1oJgORwNKOyvukPo
"""

from google.colab import files
files.upload()

import pandas as pd
df = pd.read_csv('sample.csv')

df.isnull().sum()

import seaborn as sns
import matplotlib.pyplot as plt
#visualization libraries

from IPython.core import error
#category wise sales
plt.figure(figsize=(5,8))
ax = sns.barplot(data=df,x='Category',y='Sales', estimator='sum', errorbar=None)

for container in ax.containers:
  ax.bar_label(container, fmt='%.0f', padding=3)
plt.show()

# find the sales category and segment
df.columns

df[['Category', 'Segment', 'Sales']] #multivariate analysis

plt.figure(figsize=(12,5))
ax = sns.barplot(data=df, x='Category', y='Sales', hue='Segment', errorbar=None)
plt.title('Category and segment wise sales')

for container in ax.containers:
  ax.bar_label(container, fmt='%.0f', padding=3)
plt.show()

#find the total sales category and region wise
plt.figure(figsize=(12,8))
ax = sns.barplot(data=df, x='Category', y='Sales', hue='Region', estimator='sum',errorbar=None)
plt.title('Category and region wise sales')

for container in ax.containers:
  ax.bar_label(container, fmt='%.0f', padding=3)
plt.show()

#boxplot: show outliers;
#used only in numerical dataset
num_col = df.select_dtypes(exclude=['object'])
num_col

plt.figure(figsize=(12,5))
sns.boxplot(num_col)

num_col.describe()

#Distribution plot
#skewness of data
sns.distplot(df['Profit'])

df2 = df.copy()

df2 = df2[df2['Profit']> -2000] #filter the rows

sns.displot(df2['Profit'])

sns.boxplot(df2['Profit'])

#Displot
#Outliers:Histogram:Histplot
sns.histplot(df2['Profit'], bins=30)

#scatter plot:
#relationship between two variables
sns.scatterplot(x=df2['Sales'], y=df2['Profit'])

df.columns

df = df.drop(columns=['Order Date', 'Ship Date'],axis=1)

import numpy as np
start_date = pd.Timestamp("2024-01-01")
end_date = pd.Timestamp("2024-12-31")

df['Date'] = pd.to_datetime(
    np.random.randint(
        start_date.value//10**9,
        end_date.value//10**9,
        size=len(df)
    ),
    unit='s'
)

df

#find the monthly sales
df['Month'] = df['Date'].dt.to_period('M').astype(str)

monthly_sales = df.groupby('Month')['Sales'].sum().reset_index()

#line chart
plt.figure(figsize=(12,5))
sns.lineplot(data=monthly_sales, x='Month', y='Sales',marker='o')
plt.title('Monthly sales')
plt.xticks(rotation=45)

#find the sales category wise across different month
monthly_sales = df.groupby(['Month', 'Category'])['Sales'].sum().reset_index()

monthly_sales

#line chart
plt.figure(figsize=(12,5))
sns.lineplot(data=monthly_sales, x='Month', y='Sales', hue='Category', marker='o')
plt.title('Monthly sales category')
plt.xticks(rotation=45)

